version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - webapp/target/webapp.war
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - appspec.yml
   
  discard-paths: yes
