version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install maven -y 
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
     - webapp/target/webapp.war
     - scripts/server_start.sh
     - scripts/server_stop.sh
     - appspec.yml
   
  discard-paths: yes
